### ISSUE TITLE
[Pingvin-share] Make default securityContext compliant with "restricted" pod security

### ISSUE THREAD

**Issue by mossroy** [DLAKE-IO/helm-charts#14]
It's great that it's possible to configure the securityContext.
I manage to run pingvin-share in a namespace configured with "restricted" pod security (see https://kubernetes.io/docs/concepts/security/pod-security-standards/), by overriding the default securityContext with (inside my values.yaml):

```
securityContext:
  runAsUser: 1000
  runAsGroup: 2000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  seccompProfile:
    type: RuntimeDefault
```

It's not far from the default securityContext provided inside the Helm chart.
It might be an improvement to make this default securityContext compliant with "restricted" pod security.

I suppose the only really necessary addition is:
`allowPrivilegeEscalation: false`
