### ISSUE TITLE
[Pingvin-share] Upgrade docker image to 0.21.3 (or newer)

### ISSUE THREAD

**Issue by mossroy** [DLAKE-IO/helm-charts#15]
The Helm chart currently deploys v0.17.0 by default. Latest version is v0.21.3

The values.yaml allows to manually override the tag, but it's not enough: if you only do so, it complains it cannot write inside some subdirectories of /var/lib/nginx, and in /run/nginx

I managed to manually workaround that by adding some emptyDir volumes, but it's clearly not ideal:
```
extraVolumes:
  - name: var-lib-nginx
    emptyDir: {}
  - name: var-lib-nginx-logs
    emptyDir: {}
  - name: var-lib-nginx-tmp
    emptyDir: {}
  - name: run-nginx
    emptyDir: {}
extraVolumeMounts:
  - mountPath: "/var/lib/nginx"
    name: var-lib-nginx
  - mountPath: "/var/lib/nginx/logs"
    name: var-lib-nginx-logs
  - mountPath: "/var/lib/nginx/tmp"
    name: var-lib-nginx-tmp
  - mountPath: "/run/nginx"
    name: run-nginx
```
